### ISSUE TITLE
이스터에그 동작 에러

### ISSUE THREAD

**Issue by tleunwlp** [ffe4el/SoftEngTeam#9]
이스터에그 동작 에러

**Comment by ffe4el** [comment]
이스터에그 동작이 어떻게 에러가 난다는 말씀이신가요??

**Comment by tleunwlp** [comment]
처음 정수 input 받을 때만 이스터에그가 동작합니다.!

**Comment by ffe4el** [comment]
만약에 5 입력하고 - 입력하고 7532입력하면 print("Software Engineering Class") 하고 return 은 None으로 해주고 끝내도 될까요?

**Comment by ffe4el** [comment]
근데 이렇게 되면 main함수 종료가 되진 않습니다! 종료가 되도록 만들어야될까요? 일단 main함수가 종료될 수 있도록 에러 수정해서 올리겠습니다!
